CREATE USER voting_user IDENTIFIED BY voting123;

GRANT CONNECT, RESOURCE TO voting_user;

ALTER USER voting_user QUOTA UNLIMITED ON USERS;

CONNECT voting_user/voting123;

CREATE TABLE CANDIDATES
(
    CANDIDATE_ID NUMBER PRIMARY KEY,
    CANDIDATE_NAME VARCHAR2(100),
    PARTY_NAME VARCHAR2(100)
);

CREATE TABLE VOTES
(
    VOTE_ID NUMBER PRIMARY KEY,
    VOTER_NAME VARCHAR2(100),
    CANDIDATE_ID NUMBER,
    VOTE_DATE DATE,
    CONSTRAINT FK_CANDIDATE
    FOREIGN KEY (CANDIDATE_ID)
    REFERENCES CANDIDATES(CANDIDATE_ID)
);

INSERT INTO CANDIDATES VALUES (101,'Ramesh','ABC Party');
INSERT INTO CANDIDATES VALUES (102,'Suresh','XYZ Party');
INSERT INTO CANDIDATES VALUES (103,'Mahesh','National Party');

INSERT INTO VOTES VALUES (1,'Ravi',101,SYSDATE);
INSERT INTO VOTES VALUES (2,'Kiran',102,SYSDATE);
INSERT INTO VOTES VALUES (3,'Priya',101,SYSDATE);

COMMIT;

SELECT * FROM CANDIDATES;

SELECT * FROM VOTES;